apiVersion: v1
kind: ConfigMap
metadata:
  name: school-ceo-config
data:
  FRONTEND_URL: "http://frontend:80"
  BACKEND_URL: "http://backend:5000"
  NEXT_PUBLIC_API_URL: "http://backend:5000"
  PORT: "5000"
